### ISSUE TITLE
Error while running a scoring job in batch mode

### ISSUE THREAD

**Issue by mohsinkhalid122** [ThinkBigAnalytics/AoaDockerComposeDemos#41]
Hi I'm facing an error while I run a deployed model in batch mode. Below is the error:

*** Reading local file: /usr/local/airflow/logs/e903e328-4ae5-4be4-8e9c-4f094890f87b/execute_model_k8s/2021-01-24T21:00:00+00:00/1.log
[2021-01-24 22:15:26,089] {{taskinstance.py:1150}} ERROR - Service host/port is not set.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/operators/kubernetes_pod_operator.py", line 273, in execute
    config_file=self.config_file)
  File "/usr/local/lib/python3.7/site-packages/airflow/kubernetes/kube_client.py", line 103, in get_kube_client
    client_conf = _get_kube_config(in_cluster, cluster_context, config_file)
  File "/usr/local/lib/python3.7/site-packages/airflow/kubernetes/kube_client.py", line 41, in _get_kube_config
    config.load_incluster_config()
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/incluster_config.py", line 94, in load_incluster_config
    cert_filename=SERVICE_CERT_FILENAME).load_and_set()
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/incluster_config.py", line 45, in load_and_set
    self._load_config()
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/incluster_config.py", line 51, in _load_config
    raise ConfigException("Service host/port is not set.")
kubernetes.config.config_exception.ConfigException: Service host/port is not set.

**Comment by mohsinkhalid122** [comment]
@willfleury

**Comment by willfleury** [comment]
@mohsinkhalid122 I'm not sure I understand how you are getting this - it is talking about kubernetes but you are running in local. You seem to have had this problem before when you reported issue #26 but it went away? How did you resolve that as we did not fix anything. 

Also, issue #29 - how did you resolve that in the end? Neither of them should have been an issue and we didn't make any fixes that would have resolved either issue..

What version are you using?

**Comment by mohsinkhalid122** [comment]
@willfleury Yeah I faced the same issue #26 when I recently deployed the model with the old 2.7.1 docker-config.yaml. Then I ran AOps again with the new committed docker-config.yaml(I think you guys have made some changes in the Airflow Scheduler) and got this error.

**Comment by mohsinkhalid122** [comment]
Hi I deleted and re-downloaded the all images the issues got resolved by themselves.

**Comment by willfleury** [comment]
@mohsinkhalid122 you deleted all images?  That shouldn't fix anything.. How do you stop / start / cleanup your docker-compose setup after e.g. you make changes to the yaml file? Make sure to do "docker-compose down" etc

See the troubleshooting section here. https://github.com/ThinkBigAnalytics/AoaDockerComposeDemos#troubleshooting

**Comment by mohsinkhalid122** [comment]
@willfleury I ran this command 
`docker rmi $(docker images -a --format '{{.Repository}}:{{.Tag}}' | grep 'thinkbiganalytics/aoa-')`

and then re-ran docker-compose up, that sort of did the trick, I think @Christian-TD did resolve issue #26.

btw I'm still facing issue #29, I've commented on the issue
